from similar_teams.similar_teams_z_sum_filtered import similar_teams_z_sum_filtered
from effective_stats.first_model_no_scipy import first_model_no_scipy

opposition_representation = {
  "score": 0,
  "half_time": 0,
  "time_in_possession": 0,
  "all_runs": 0,
  "all_run_metres": 0,
  "post_contact_metres": 0,
  "line_breaks": 0,
  "tackle_breaks": 0,
  "average_set_distance": 0,
  "kick_return_metres": 0,
  "offloads": 0,
  "receipts": 0,
  "total_passes": 0,
  "dummy_passes": 0,
  "kicks": 0,
  "kicking_metres": 0,
  "forced_drop_outs": 0,
  "bombs": 0,
  "grubbers": 0,
  #"forty_twenty": 0,
  "tackles_made": 0,
  "missed_tackles": 0,
  "intercepts": 0,
  "ineffective_tackles": 0,
  "errors": 0,
  "penalties_conceded": 0,
  "ruck_infringements": 0,
  "inside_ten_metres": 0,
  "interchanges_used": 0,
  "completion_rate": 0,
  "average_play_ball_speed": 0,
  "kick_defusal": 0,
  "effective_tackle": 0,
  "tries": 0,
  "conversions": 0,
  "conversions_missed": 0,
  "penalty_goals": 0,
  "penalty_goals_missed": 0,
  "sin_bins": 0,
  "on_reports": 0,
  #"one_point_field_goals": 0,
  #"one_point_field_goals_missed": 0,
  #"two_point_field_goals": 0,
  #"two_point_field_goals_missed": 0,
}

opposition_sides = similar_teams_z_sum_filtered(opposition_representation, 200)
first_model_no_scipy(opposition_sides)