CREATE TABLE matches (
    -- Home stats
    home text,
    home_score int,
    time_in_possession_h int,
    all_runs_h int,
    all_run_metres_h int,
    post_contact_metres_h int,
    line_breaks_h int,
    tackle_breaks_h int,
    average_set_distance_h numeric(7, 2),
    kick_return_metres_h int,
    offloads_h int,
    receipts_h int,
    total_passes_h int,
    dummy_passes_h int,
    kicks_h int,
    kicking_metres_h int,
    forced_drop_outs_h int,
    bombs_h int,
    grubbers_h int,
    forty_twenty_h int,
    tackles_made_h int,
    missed_tackles_h int,
    intercepts_h int,
    ineffective_tackles_h int,
    errors_h int,
    penalties_conceded_h int,
    ruck_infringements_h int,
    inside_ten_metres_h int,
    interchanges_used_h int,
    completion_rate_h numeric(5,2),
    average_play_ball_speed_h numeric(5, 2),
    kick_defusal_h numeric(5,2),
    effective_tackle_h numeric(5,2),
    tries_h int,
    conversions_h int,
    conversions_missed_h int,
    penalty_goals_h int,
    penalty_goals_missed_h int,
    sin_bins_h int,
    on_reports_h int,
    one_point_field_goals_h int,
    one_point_field_goals_missed_h int,
    two_point_field_goals_h int,
    two_point_field_goals_missed_h int,
    half_time_h int,

    -- Away stats
        away text,
    away_score int,
    time_in_possession_a int,
    all_runs_a int,
    all_run_metres_a int,
    post_contact_metres_a int,
    line_breaks_a int,
    tackle_breaks_a int,
    average_set_distance_a numeric(6, 2),
    kick_return_metres_a int,
    offloads_a int,
    receipts_a int,
    total_passes_a int,
    dummy_passes_a int,
    kicks_a int,
    kicking_metres_a int,
    forced_drop_outs_a int,
    bombs_a int,
    grubbers_a int,
    forty_twenty_a int,
    tackles_made_a int,
    missed_tackles_a int,
    intercepts_a int,
    ineffective_tackles_a int,
    errors_a int,
    penalties_conceded_a int,
    ruck_infringements_a int,
    inside_ten_metres_a int,
    interchanges_used_a int,
    completion_rate_a numeric(5,2),
    average_play_ball_speed_a numeric(5, 2),
    kick_defusal_a numeric(5,2),
    effective_tackle_a numeric(5, 2),
    tries_a int,
    conversions_a int,
    conversions_missed_a int,
    penalty_goals_a int,
    penalty_goals_missed_a int,
    sin_bins_a int,
    on_reports_a int,
    one_point_field_goals_a int,
    one_point_field_goals_missed_a int,
    two_point_field_goals_a int,
    two_point_field_goals_missed_a int,
    half_time_a int,

    -- Other match data
    season int,
    round int,
    venue text,
    match_date_utc timestamptz,
    match_centre_url text,
    overall_first_try_scorer text,
    overall_first_try_minute int,
    overall_first_try_round text,
    ref_names text[],
    ref_positions text[],
    main_ref text,
    ground_condition text,
    weather_condition text,
    match_id serial primary key
);
