-- Exactly the same data as team_stats, but taking z-scores of each stat for each season to ensure that analysis can be done without biases
CREATE TABLE team_stats_z (
  match_id  integer NOT NULL REFERENCES match_data(match_id) ON DELETE CASCADE,
  team      text    NOT NULL,
  is_home   boolean NOT NULL, -- true = home, false = away
  score     double precision,
  half_time double precision,

  time_in_possession double precision,
  all_runs double precision,
  all_run_metres double precision,
  post_contact_metres double precision,
  line_breaks double precision,
  tackle_breaks double precision,
  average_set_distance double precision,
  kick_return_metres double precision,
  offloads double precision,
  receipts double precision,
  total_passes double precision,
  dummy_passes double precision,
  kicks double precision,
  kicking_metres double precision,
  forced_drop_outs double precision,
  bombs double precision,
  grubbers double precision,
  forty_twenty double precision,
  tackles_made double precision,
  missed_tackles double precision,
  intercepts double precision,
  ineffective_tackles double precision,
  errors double precision,
  penalties_conceded double precision,
  ruck_infringements double precision,
  inside_ten_metres double precision,
  interchanges_used double precision,
  completion_rate double precision,
  average_play_ball_speed double precision,
  kick_defusal double precision,
  effective_tackle double precision,
  tries double precision,
  conversions double precision,
  conversions_missed double precision,
  penalty_goals double precision,
  penalty_goals_missed double precision,
  sin_bins double precision,
  on_reports double precision,
  one_point_field_goals double precision,
  one_point_field_goals_missed double precision,
  two_point_field_goals double precision,
  two_point_field_goals_missed double precision,

  PRIMARY KEY (match_id, is_home)
);